


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 473)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_lable = QtWidgets.QLabel(self.centralwidget)
        self.title_lable.setGeometry(QtCore.QRect(100, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_lable.setFont(font)
        self.title_lable.setObjectName("title_lable")
        self.amount_label = QtWidgets.QLabel(self.centralwidget)
        self.amount_label.setGeometry(QtCore.QRect(140, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.amount_label.setFont(font)
        self.amount_label.setObjectName("amount_label")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(240, 190, 113, 20))
        self.input_amount.setObjectName("input_amount")
        self.from_label = QtWidgets.QLabel(self.centralwidget)
        self.from_label.setGeometry(QtCore.QRect(90, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.from_label.setFont(font)
        self.from_label.setObjectName("from_label")
        self.to_label = QtWidgets.QLabel(self.centralwidget)
        self.to_label.setGeometry(QtCore.QRect(110, 130, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.to_label.setFont(font)
        self.to_label.setObjectName("to_label")
        self.exchange_Button = QtWidgets.QPushButton(self.centralwidget)
        self.exchange_Button.setGeometry(QtCore.QRect(160, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exchange_Button.setFont(font)
        self.exchange_Button.setObjectName("exchange_Button")
        self.output_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.output_amount.setGeometry(QtCore.QRect(160, 310, 131, 21))
        self.output_amount.setObjectName("output_amount")
        self.clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_Button.setGeometry(QtCore.QRect(20, 370, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.clear_Button.setFont(font)
        self.clear_Button.setObjectName("clear_Button")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(240, 91, 121, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(240, 141, 121, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_lable.setText(_translate("MainWindow", "Foreign Exchange Currency"))
        self.amount_label.setText(_translate("MainWindow", "Amount :"))
        self.from_label.setText(_translate("MainWindow", "Currency from :"))
        self.to_label.setText(_translate("MainWindow", "Currency to :"))
        self.exchange_Button.setText(_translate("MainWindow", "Exchange"))
        self.clear_Button.setText(_translate("MainWindow", "clear all"))
        self.comboBox.setItemText(0, _translate("MainWindow", "USD"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EUR"))
        self.comboBox.setItemText(2, _translate("MainWindow", "GBP"))
        self.comboBox.setItemText(3, _translate("MainWindow", "CAD"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "USD"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "EUR"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "GBP"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "CAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
